export {default as YoutubeSVG} from './youtube.svg';
export {default as SwipeSVG} from './swipe.svg';
export {default as DeviantartSVG} from './deviant-art.svg';
export {default as ImageSVG} from './image.svg';
export {default as InfoSVG} from './info.svg';
export {default as LoadingSVG} from './loading.svg';
export {default as CancelSVG} from './cancel.svg';
export {default as ConfettiSVG} from './confetti.svg';
export {default as BreathingSVG} from './breathing.svg';