import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from '@/lib/utils'
import "./globals.css";
import { ThemeProvider } from "@/components/context/themeProvider";
import LayoutProvider from "@/components/context/layoutProvider";
import UserSessionProvider from "@/components/context/userProvider";
import { Toaster } from "@/components/ui/toaster";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserSessionProvider>
            <LayoutProvider>
                {children}
              </LayoutProvider>
          </UserSessionProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
