import './globals.css'

import type { Metadata } from 'next'
import { Inter, Poppins} from 'next/font/google'

import AuthProvider from '@/lib/utils/contexts/Auth'
import NavBar from '@/components/layout/navBar'

const inter = Poppins({ subsets: ['latin'], weight: ["100", "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"] })

export const metadata: Metadata = {
  title: 'HyperSets',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
            <NavBar />
            {children}
          </AuthProvider>
      </body>
    </html>
  )
}
