import './globals.css'

import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'

import NavBar from '@/components/layout/MobileNavDrawer'
import UserSessionProvider from '@/lib/contexts/UserSession'
import { ToastProvider } from '@radix-ui/react-toast'
import LayoutProvider from '@/lib/contexts/Layout'

const inter = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata: Metadata = {
  title: 'HyperSets',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserSessionProvider>
          <LayoutProvider>
            {children}
          </LayoutProvider>
        </UserSessionProvider>
      </body>
    </html>
  )
}
